g = love.graphics
k = love.keyboard
gameWidth = g.getWidth()
gameHeight = g.getHeight()
timeScale = 1 -- Time will be multiplied by this constant
bounceFactor = 1.5 -- Bouncing factor on cannonball collisions
windEnabled = true -- Enable/disable wind
maxUnstuckIterations = 1024 -- Maximum number of attempts to get unstuck from collisions
pi = math.pi
doublePi = 2 * pi
halfPi = pi / 2
quarterPi = pi / 4
threeQuartersPi = pi * 0.75
radToDeg = 180 / pi
